// Expierences
export const FETCH_USER_EXPERIENCES_REQUEST = "FETCH_USER_EXPERIENCES_REQUEST";
export const FETCH_USER_EXPERIENCES_SUCCESS = "FETCH_USER_EXPERIENCES_SUCCESS";
export const FETCH_USER_EXPERIENCES_FAILURE = "FETCH_USER_EXPERIENCES_FAILURE";

// Search
export const FETCH_SEARCH_RESULT_REQUEST = "FETCH_SEARCH_RESULT_REQUEST";
export const FETCH_SEARCH_RESULT_SUCCESS = "FETCH_SEARCH_RESULT_SUCCESS";
export const FETCH_SEARCH_RESULT_FAILURE = "FETCH_SEARCH_RESULT_FAILURE";
