// Expierences
export const FETCH_USER_EXPERIENCES_REQUEST = "FETCH_USER_EXPERIENCES_REQUEST";
export const FETCH_USER_EXPERIENCES_SUCCESS = "FETCH_USER_EXPERIENCES_SUCCESS";
export const FETCH_USER_EXPERIENCES_FAILURE = "FETCH_USER_EXPERIENCES_FAILURE";

// Searches
export const FETCH_SEARCH_RESULT_REQUEST = "FETCH_SEARCH_RESULT_REQUEST";
export const FETCH_SEARCH_RESULT_SUCCESS = "FETCH_SEARCH_RESULT_SUCCESS";
export const FETCH_SEARCH_RESULT_FAILURE = "FETCH_SEARCH_RESULT_FAILURE";

// Users
export const CREATE_USER_REQUEST = "CREATE_USER_REQUEST";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const CREATE_USER_FAILURE = "CREATE_USER_FAILURE";
export const EDIT_USER_REQUEST = "EDIT_USER_REQUEST";
export const EDIT_USER_SUCCESS = "EDIT_USER_SUCCESS";
export const EDIT_USER_FAILURE = "EDIT_USER_FAILURE";
export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAILURE = "GET_USER_FAILURE";
