export const FETCH_USER_EXPERIENCES_REQUEST = "FETCH_USER_EXPERIENCES_REQUEST";
export const FETCH_USER_EXPERIENCES_SUCCESS = "FETCH_USER_EXPERIENCES_SUCCESS";
export const FETCH_USER_EXPERIENCES_FAILURE = "FETCH_USER_EXPERIENCES_FAILURE";
