-- DDL generated by Postico 1.5.14
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE experiences (
    id SERIAL PRIMARY KEY,
    user_id integer REFERENCES users(id),
    title text,
    description text,
    years integer,
    months integer,
    published boolean DEFAULT false,
    "order" integer
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX experiences_pkey ON experiences(id int4_ops);
