-- DDL generated by Postico 1.5.14
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE firebase_user_map (
    user_id integer NOT NULL REFERENCES users(id) UNIQUE,
    firebase_id text NOT NULL UNIQUE
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX firebase_user_map_user_id_key ON firebase_user_map(user_id int4_ops);
CREATE UNIQUE INDEX firebase_user_map_firebase_id_key ON firebase_user_map(firebase_id text_ops);
