name: End-to-end tests
on: [push]
env:
  CYPRESS_HOST: "http://localhost:8000"
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          yarn install
          SECRET_COOKIE_PASSWORD=THE_SECRET_KEY_FOR_SESSION_STORAGE yarn build &
           yarn firebase login --token "$FIREBASE_TOKEN"
         env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      - name: Start
        run: |
          NODE_ENV=development yarn start &
          yarn emulator &
      - name: Run Cypress test
        uses: cypress-io/github-action@v2
        with:
          command: yarn cy:build
