name: End-to-end tests
on: [push]
env:
  CYPRESS_HOST: "http://localhost:8000"
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          yarn install
          SECRET_COOKIE_PASSWORD=THE_SECRET_KEY_FOR_SESSION_STORAGE yarn build
      - name: Start Emulator
        run: |
          yarn emulator --token "$FIREBASE_TOKEN" --project kontaktar-is &
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      - name: Run Cypress test
        uses: cypress-io/github-action@v2
        with:
          command: yarn cy:build
          start: yarn next start
          browser: chrome
